PUT http://localhost:3003/api/stocks/5e7e2994324c9729da548998
Content-Type: application/json

{
        "ticker": "IVE BEEN UPDATED",
        "name": "Apple Corporation",
        "shares": 10,
        "price": 100
}