POST http://localhost:3003/api/portfolio/sell
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlaXRoIiwiaWQiOiI1ZTgzOTQzYmQ5MzU0YjEzOTkxOGMwMzQiLCJpYXQiOjE1ODU2ODE1MTJ9.XRKEfDvmcQCfdqAdd6b9Th-m8WbIKOcRh_3xdLTSaXg

{
        "ticker": "GOOG",
        "shares": 1,
        "price": 85
}
